[package]
name = "HelloBlockchain"
version = "0.0.0"

[addresses]
HelloBlockchain = "_"
StakingContract = "_"

[dependencies]
AptosFramework = { local = "/aptos-core/aptos-move/framework/aptos-framework" }
